### ISSUE TITLE
[FE/Task]Main, Detail페이지 구현 PostThumnails 컴포넌트  구현하기

### ISSUE THREAD

**Issue by KAPUIST** [codestates/Music-Flower#15]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 각각의 페이지들 구현 

### TODO
1. [x] Main 페이지 구현
2. [x] Detail 페이지 구현
3. [x] PostThumnail 컴포넌트 구현

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Urgency: ``Middle`
