### ISSUE TITLE
[BE/Task] sequelize 구현하기

### ISSUE THREAD

**Issue by kim-kyoungyeon** [codestates/Music-Flower#24]
### ISSUE
- Group:   `server`
- Type: `feature`
- Detail: DB의 sequelize seeder에 대해 연구하고 중간 미팅때 연구한것을 바탕으로 seeder 작성

### TODO
1. [x] 새로운 tables를 sequelize 한다 
2. [x] seeder와 records를 만든다 
3. [x] 위 두가지 문제가 해결 되었을 경우 db flow 에 대한 업무 분배를 한다.  

### Estimated time
>  ### `3h`

### Labels
- Estimated time: `E: 3h`
- Group :  `server`
 
- Urgency:  `Middle`,
